### ISSUE TITLE
Skills and Combat Skills dont get imported

### ISSUE THREAD

**Issue by tomsaath** [ntfoster/optolith-to-foundry#1]
The Skills and Combat Skills dont get importet in my first test.

Testlanguage: German

(sorry my english is not very good)

**Comment by ntfoster** [comment]
I see the problem. I thought German and English skills IDs were the same, but they are not.

I will fix this later.

Danke schön!

**Comment by ntfoster** [comment]
I think this is fixed now. I have released version 0.3.1. Please update when you can and let me know if there is a problem.

**Comment by tomsaath** [comment]
Works, great job.
